### ISSUE TITLE
Can't authenticate with app passwords - FB says 401

### ISSUE THREAD

**Issue by jkufner** [dequis/purple-facebook#298] opened 2017-02-23 22:42 UTC
Hello,
I'm getting the following message for last two days and I'm very sure my password is correct. I even tried a new app password (twice).

```
User: j***@k***: Disconnected from legacy network with error Invalid username or password (401)
Component.RAW: RAW DATA OUT <message from="facebook.f***" to="j***@k***" type="chat"><body>Invalid username or password (401)</body><spectrumerror error="2" xmlns="http://spectrum.im/error">CONNECTION_ERROR_AUTHENTICATION_FAILED</spectrumerror></message>
```

Do you have any idea what may be wrong?

I'm using Spectrum2 on Debian Jessie.

Thank you :)

**Comment by dequis** [comment] 2017-02-24 00:37
No idea, that log doesn't say much. I don't know how to enable proper debug logs in spectrum, so, try with pidgin.

**Comment by mw80** [comment] 2017-02-24 09:18
same issue here. started today and was working before

**Comment by mw80** [comment] 2017-02-24 09:23
I solved the issue by switching to the dialog password.

**Comment by jkufner** [comment] 2017-02-24 09:46
@mw80 Thank you! The primary login password works. It looks like Facebook screwed up something somewhere.

Is there a difference in API when using app password? (Or recent change in API.)

**Comment by dequis** [comment] 2017-02-25 07:09
Yeah, confirmed, it's the app passwords. Looks like the official apps are affected by this too.

**Comment by languitar** [comment] 2017-03-02 08:51
Is there any external information on the app password issue or something that FB knows about?

**Comment by lenny87** [comment] 2017-03-02 09:07
It started working again

**Comment by languitar** [comment] 2017-03-02 09:08
Not for me :( Still a 401

**Comment by dequis** [comment] 2017-03-02 15:17
>Is there any external information on the app password issue or something that FB knows about?

I've sent a bug report through the "report problem" thing in the android messenger app a few days ago, but those things don't have a lot of feedback. It goes to a bug reporting API endpoint and returns a bug id, so it's probably somewhere in their bug tracker.

I've heard from some users that it works for them - must be something that only affects some servers. But you can't really target a specific server with the way facebook routes stuff.

FWIW, if you needed app passwords for 2fa, you can enter the real password, then change the password field with the auth code you receive.

**Comment by jaymzh** [comment] 2017-03-09 23:39
Reported internally, I'll see if we can get this sorted out.

**Comment by dequis** [comment] 2017-03-12 08:29
Just checked and this works for me locally but not when using tor.

Response headers of good request:

```
x-fb-rev: 2886434
x-fb-trace-id: DtEQUde4DMS
X-FB-Debug: Ewjg9jad93lAfxIT2N/3040L3A+p55bXkCovUeWbdi1mJIPELrPi+h2N0DoOD0GGnI5qCTQIP79mkoisXQcp7g==
```

Response headers of bad request:

```
x-fb-rev: 2885019
x-fb-trace-id: Fsf0ejnC/Qx
X-FB-Debug: G5zLU7gNEf8ZOCmDNLEk7DAOR5hSiGFM/XQKkyIvow51pwnVVBB/R6PQZt9D06pwRmtR5kHqMDP09A+lY+7zlQ==
```

**Comment by jaymzh** [comment] 2017-03-12 08:49
I think it depends on a lot of factors if this works for you or not... I expect this to get fixed next week.

**Comment by dequis** [comment] 2017-03-12 17:19
Yeah I'm just really curious about what combination of gatekeeper madness is going on here, but it looks it's a black box that's going to stay like that (that's okay, it's part of the fun)

**Comment by RoyMagneIndrebo** [comment] 2017-03-15 06:23
Started working again for me today.

**Comment by languitar** [comment] 2017-03-15 09:26
Same for me, but not completely reliably

**Comment by jaymzh** [comment] 2017-03-15 13:53
I believe this should now be fixed for everyone...

**Comment by dequis** [comment] 2017-03-18 03:05
So I guess it's safe to close this now. Thanks @jaymzh!

**Closed by dequis** 2017-03-18 03:05 UTC
