### ISSUE TITLE
Null value for $.viewer.message_threads.unread_count

### ISSUE THREAD

**Issue by josx** [dequis/purple-facebook#393] opened 2017-12-05 12:15 UTC
Today I tried to connect as usual and i keep recieving:
```Null value for $.viewer.message_threads.unread_count```

I dont know if it is related with #309 (similar)

Using: 
```
Pidgin 2.12.0 (libpurple 2.12.0)
Purple-facebook  0.9.5-9ff9acf9fa14
```

**Comment by rrthomas** [comment] 2017-12-05 12:16
Me too. I'm using the same release, from the PPA: 20171004~4aa77de~9ff9acf9fa14~137

**Comment by dequis** [comment] 2017-12-05 12:28
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by quaired** [comment] 2017-12-05 12:43
Just got the same issue now.

**Comment by josx** [comment] 2017-12-05 13:04
tail of the log
```
(09:20:08) http: Got main header with code 200
(09:20:08) http: Got header: ETag: "(09:20:08) http: Got main header with code 200
(09:20:08) http: Got header: ETag: "9db76d99c9975f940d9f6b9f339a34712469b3dc"
(09:20:08) http: Got header: fb-graphql-error-count: 3
(09:20:08) http: Got header: Access-Control-Expose-Headers: X-FB-Debug, X-Loader-Length
(09:20:08) http: Got header: Access-Control-Allow-Methods: OPTIONS
(09:20:08) http: Got header: Access-Control-Allow-Credentials: true
(09:20:08) http: Got header: Strict-Transport-Security: max-age=15552000; preload
(09:20:08) http: Got header: x-fb-trace-id: E1ZYvJg5MYY
(09:20:08) http: Got header: x-fb-rev: 3501271
(09:20:08) http: Got header: Expires: Sat, 01 Jan 2000 00:00:00 GMT
(09:20:08) http: Got header: Content-Type: application/json; charset=UTF-8
(09:20:08) http: Got header: facebook-api-version: v1.0
(09:20:08) http: Got header: Cache-Control: private, no-cache, no-store, must-revalidate
(09:20:08) http: Got header: Pragma: no-cache
(09:20:08) http: Got header: Vary: Origin
(09:20:08) http: Got header: Access-Control-Allow-Origin: https://graph.facebook.com
(09:20:08) http: Got header: Vary: Accept-Encoding
(09:20:08) http: Got header: Content-Encoding: gzip
(09:20:08) http: Got header: X-FB-Debug: wK5WldIq8fkVTHgqOMIXh9oluQ0atcF98z9UNeO10yHWG8BK0hkXCfQ2A6vA+fY4VD6T1DLgbOmsSuTFh5Hyyg==
(09:20:08) http: Got header: Date: Tue, 05 Dec 2017 12:20:08 GMT
(09:20:08) http: Got header: Connection: keep-alive
(09:20:08) http: Got header: Content-Length: 308
(09:20:08) http: Got headers end
(09:20:08) http: Got response headers: ETag: "9db76d99c9975f940d9f6b9f339a34712469b3dc"
fb-graphql-error-count: 3
Access-Control-Expose-Headers: X-FB-Debug, X-Loader-Length
Access-Control-Allow-Methods: OPTIONS
Access-Control-Allow-Credentials: true
Strict-Transport-Security: max-age=15552000; preload
x-fb-trace-id: E1ZYvJg5MYY
x-fb-rev: 3501271
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Content-Type: application/json; charset=UTF-8
facebook-api-version: v1.0
Cache-Control: private, no-cache, no-store, must-revalidate
Pragma: no-cache
Vary: Origin
Access-Control-Allow-Origin: https://graph.facebook.com
Vary: Accept-Encoding
Content-Encoding: gzip
X-FB-Debug: wK5WldIq8fkVTHgqOMIXh9oluQ0atcF98z9UNeO10yHWG8BK0hkXCfQ2A6vA+fY4VD6T1DLgbOmsSuTFh5Hyyg==
Date: Tue, 05 Dec 2017 12:20:08 GMT
Connection: keep-alive
Content-Length: 308
(09:20:08) http: releasing a socket: 0x557495e4bf60
(09:20:08) http: Request 0x557495a21100 performed successfully.
(09:20:08) facebook: HTTP Response (0x557495a21100):
(09:20:08) facebook:   Response Error: 200
(09:20:08) facebook:   Response Data: {"viewer":{"actor":{"__type__":{"name":"User"},"id":"1140415216","name":"Jos\u00e9 Luis Di Biase","profile_picture":{"uri":"https:\/\/scontent.xx.fbcdn.net\/v\/t1.0-1\/p50x50\/13669692_10209801561972663_13802411906100362_n.jpg?_nc_ad=z-m&_nc_cid=0&oh=0a6d8e7c5bdf10744b586e3029563ab0&oe=5AD5BD20"}},"message_threads":{"unread_count":null,"sync_sequence_id":null,"nodes":[]}}}
(09:20:08) facebook: Parsing JSON: {"viewer":{"actor":{"__type__":{"name":"User"},"id":"1140415216","name":"Jos\u00e9 Luis Di Biase","profile_picture":{"uri":"https:\/\/scontent.xx.fbcdn.net\/v\/t1.0-1\/p50x50\/13669692_10209801561972663_13802411906100362_n.jpg?_nc_ad=z-m&_nc_cid=0&oh=0a6d8e7c5bdf10744b586e3029563ab0&oe=5AD5BD20"}},"message_threads":{"unread_count":null,"sync_sequence_id":null,"nodes":[]}}}

(09:20:08) connection: Connection error on 0x55749433cef0 (reason: 0 description: Null value for $.viewer.message_threads.unread_count)
(09:20:08) http: destroying socket: 0x557495e4bf60
(09:20:08) account: Disconnecting account joseluis.dibiase (0x557493e21450)
(09:20:08) connection: Disconnecting connection 0x55749433cef0
(09:20:08) facebook: Writing 14 (flags: 0x0)
(09:20:08) facebook:   00000000  e0 00                                             |..|
(09:20:08) facebook:   00000010
(09:20:08) jabber: jabber_actions: have pep: YES
(09:20:08) jabber: jabber_actions: have pep: NO
(09:20:08) connection: Destroying connection 0x55749433cef0
(09:20:11) account: Disconnecting account josx@jabber.org/ (0x557493fc5a30)
(09:20:11) connection: Disconnecting connection 0x557493cd6290
(9db76d99c9975f940d9f6b9f339a34712469b3dc"
(09:20:08) http: Got header: fb-graphql-error-count: 3
(09:20:08) http: Got header: Access-Control-Expose-Headers: X-FB-Debug, X-Loader-Length
(09:20:08) http: Got header: Access-Control-Allow-Methods: OPTIONS
(09:20:08) http: Got header: Access-Control-Allow-Credentials: true
(09:20:08) http: Got header: Strict-Transport-Security: max-age=15552000; preload
(09:20:08) http: Got header: x-fb-trace-id: E1ZYvJg5MYY
(09:20:08) http: Got header: x-fb-rev: 3501271
(09:20:08) http: Got header: Expires: Sat, 01 Jan 2000 00:00:00 GMT
(09:20:08) http: Got header: Content-Type: application/json; charset=UTF-8
(09:20:08) http: Got header: facebook-api-version: v1.0
(09:20:08) http: Got header: Cache-Control: private, no-cache, no-store, must-revalidate
(09:20:08) http: Got header: Pragma: no-cache
(09:20:08) http: Got header: Vary: Origin
(09:20:08) http: Got header: Access-Control-Allow-Origin: https://graph.facebook.com
(09:20:08) http: Got header: Vary: Accept-Encoding
(09:20:08) http: Got header: Content-Encoding: gzip
(09:20:08) http: Got header: X-FB-Debug: wK5WldIq8fkVTHgqOMIXh9oluQ0atcF98z9UNeO10yHWG8BK0hkXCfQ2A6vA+fY4VD6T1DLgbOmsSuTFh5Hyyg==
(09:20:08) http: Got header: Date: Tue, 05 Dec 2017 12:20:08 GMT
(09:20:08) http: Got header: Connection: keep-alive
(09:20:08) http: Got header: Content-Length: 308
(09:20:08) http: Got headers end
(09:20:08) http: Got response headers: ETag: "9db76d99c9975f940d9f6b9f339a34712469b3dc"
fb-graphql-error-count: 3
Access-Control-Expose-Headers: X-FB-Debug, X-Loader-Length
Access-Control-Allow-Methods: OPTIONS
Access-Control-Allow-Credentials: true
Strict-Transport-Security: max-age=15552000; preload
x-fb-trace-id: E1ZYvJg5MYY
x-fb-rev: 3501271
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Content-Type: application/json; charset=UTF-8
facebook-api-version: v1.0
Cache-Control: private, no-cache, no-store, must-revalidate
Pragma: no-cache
Vary: Origin
Access-Control-Allow-Origin: https://graph.facebook.com
Vary: Accept-Encoding
Content-Encoding: gzip
X-FB-Debug: wK5WldIq8fkVTHgqOMIXh9oluQ0atcF98z9UNeO10yHWG8BK0hkXCfQ2A6vA+fY4VD6T1DLgbOmsSuTFh5Hyyg==
Date: Tue, 05 Dec 2017 12:20:08 GMT
Connection: keep-alive
Content-Length: 308
(09:20:08) http: releasing a socket: 0x557495e4bf60
(09:20:08) http: Request 0x557495a21100 performed successfully.
(09:20:08) facebook: HTTP Response (0x557495a21100):
(09:20:08) facebook:   Response Error: 200
(09:20:08) facebook:   Response Data: {"viewer":{"actor":{"__type__":{"name":"User"},"id":"1140415216","name":"Jos\u00e9 Luis Di Biase","profile_picture":{"uri":"https:\/\/scontent.xx.fbcdn.net\/v\/t1.0-1\/p50x50\/13669692_10209801561972663_13802411906100362_n.jpg?_nc_ad=z-m&_nc_cid=0&oh=0a6d8e7c5bdf10744b586e3029563ab0&oe=5AD5BD20"}},"message_threads":{"unread_count":null,"sync_sequence_id":null,"nodes":[]}}}
(09:20:08) facebook: Parsing JSON: {"viewer":{"actor":{"__type__":{"name":"User"},"id":"1140415216","name":"Jos\u00e9 Luis Di Biase","profile_picture":{"uri":"https:\/\/scontent.xx.fbcdn.net\/v\/t1.0-1\/p50x50\/13669692_10209801561972663_13802411906100362_n.jpg?_nc_ad=z-m&_nc_cid=0&oh=0a6d8e7c5bdf10744b586e3029563ab0&oe=5AD5BD20"}},"message_threads":{"unread_count":null,"sync_sequence_id":null,"nodes":[]}}}

(09:20:08) connection: Connection error on 0x55749433cef0 (reason: 0 description: Null value for $.viewer.message_threads.unread_count)
(09:20:08) http: destroying socket: 0x557495e4bf60
(09:20:08) account: Disconnecting account joseluis.dibiase (0x557493e21450)
(09:20:08) connection: Disconnecting connection 0x55749433cef0
(09:20:08) facebook: Writing 14 (flags: 0x0)
(09:20:08) facebook:   00000000  e0 00                                             |..|
(09:20:08) facebook:   00000010
(09:20:08) jabber: jabber_actions: have pep: YES
(09:20:08) jabber: jabber_actions: have pep: NO
(09:20:08) connection: Destroying connection 0x55749433cef0
(09:20:11) account: Disconnecting account josx@jabber.org/ (0x557493fc5a30)
(09:20:11) connection: Disconnecting connection 0x557493cd6290
```

**Comment by josx** [comment] 2017-12-05 13:05
Maybe a temporal issue on the server because now it seems is working pretty well

**Comment by quaired** [comment] 2017-12-05 13:32
got mine back also. While on the subject. I tried opening facebook messenger via the messenger link. it won't open also. It may be a facebook server issue, mine is resolved now.

**Comment by dequis** [comment] 2017-12-05 20:05
So this is indeed essentially the same thing as the `sync_sequence_id` errors that happened in the past, most of them temporary errors that fixed themselves after a while. I guess something else went wrong that made it complain about `unread_count` too.

Anyway closing this as it appears to be fixed.

**Closed by dequis** 2017-12-05 20:05 UTC

**Comment by pcahyna** [comment] 2018-11-20 09:59
I had the same problem yesterday. At the same time, the web interface to facebook chat did not work either, so this error apparently reveals a server issue, not a bug in purple-facebook.

**Comment by rrthomas** [comment] 2018-11-20 10:54
I had exactly the same experience as @pcahyna. It looks as though purple-facebook should report that Facebook Messenger is not working in this situation.
