### ISSUE TITLE
Disconnecting after few minutes

### ISSUE THREAD

**Issue by zywek123** [dequis/purple-facebook#488] opened 2020-06-09 20:12 UTC
WHen i use a plugin normally, after a few minutes i receive this error.
The action attempted has been deemed abusive or is otherwise disallowed
I'm using the latest version of pidgin 2.13.0 and libpurple 2.13.0 and purple-facebook 0.9.6 from arch repo

**Comment by dequis** [comment] 2020-06-09 20:38
Duplicate of #486

**Closed by dequis** 2020-06-09 20:38 UTC
