### ISSUE TITLE
Repeating messages

### ISSUE THREAD

**Issue by klutt** [dequis/purple-facebook#437] opened 2018-09-25 18:19 UTC
A few times a day, Pidgin suddenly repeats the last message loads of my friends have sent. It's extremely annoying. It manifests itself like if my friends just sent the same message again.

**Comment by Gizmokid2005** [comment] 2018-10-04 17:02
Can confirm this is happening. Sometimes it'll be the other person's messages repeating, other times it'll be mine resending two or three times right in a row duplicating in the conversation on facebook as well.

**Comment by v3ree** [comment] 2018-10-25 07:31
Confirm issue on purple-facebook 0.9.5-1, pidgin 2.13.0-5 on Arch Linux. In chat windows a received or sent message is repeated 10+ times (at random times). It make the app unusable.

**Comment by dequis** [comment] 2019-01-05 00:14
Duplicate of https://github.com/dequis/purple-facebook/issues/280

**Closed by dequis** 2019-01-05 00:14 UTC
