### ISSUE TITLE
Proper versioning scheme

### ISSUE THREAD

**Issue by Mailaender** [dequis/purple-facebook#242] opened 2016-05-11 20:00 UTC
Something that is incremental would be required. Packaging and repositories are relying on it. https://build.opensuse.org/request/show/384723

**Comment by dequis** [comment] 2016-05-12 01:18
Duplicate of #52, #119, #145. Quoting from the last one:

>You could have your own version numbers, such as, 0.yyyymmdd.versionhash. That's what packagers normally do.

>A 1.0 stable release will probably happen soon.

But I guess I'm now in charge of releasing a 1.0, so i'll keep this open to track that.

**Comment by dequis** [comment] 2016-11-27 19:50
I released 0.9.0 a few days ago

Decided to not call it 1.0 but it's essentially a 1.0 release candidate, didn't want to appear with a 1.0 suddenly after so much time, and particularly the user agent patch needs confirmation that it improves things.

**Closed by dequis** 2016-11-27 19:50 UTC
