### ISSUE TITLE
AGAIN ???? Null value for $.viewer.message_threads.sync_sequence_id

### ISSUE THREAD

**Issue by pedrispedris** [dequis/purple-facebook#329] opened 2017-05-27 17:57 UTC
After having updated with the latest release, today I got this message
 
WHY ????

**Comment by arximboldi** [comment] 2017-06-02 15:45
Arghhh!!!

**Comment by dequis** [comment] 2017-06-03 20:48
Still happening?

**Comment by wision** [comment] 2017-06-06 11:57
@dequis Yes, still happenening.

**Comment by dequis** [comment] 2017-06-06 22:34
I mean, has it happened for every single login in the past 10 days? (or most of that time period?)

If it still happens sometimes, but not for every login, that doesn't really matter. This particular error message has been around since the beginning, but it always was a temporary server side issue, usually fixing itself after a couple of hours.

**Comment by arximboldi** [comment] 2017-06-06 22:38
For me it happens all the time.

**Comment by Novadestin** [comment] 2017-06-07 03:55
Just wanted to add that this is still happening (and it's continuous btw, it never goes away). Based on the other thread, it looks like this won't be fixed until the protocol is update or something since Facebook shut down support for older versions.

**Comment by wision** [comment] 2017-06-07 06:58
@dequis  It's been happening to me every day for past ~3 months.

**Comment by felagund** [comment] 2017-06-07 10:00
Yes, I has been happening to me for the past twelve hours or so (I think it is happening more now seing the activity here).

**Comment by kelpier** [comment] 2017-06-07 10:06
Yeah, just started happening to me too in the last 12 hours or so.

**Comment by dequis** [comment] 2017-06-07 16:53
@wision 3 months means you're not using the latest version, please check the version in buddy list -> help menu -> plugin information, upgrade, and ensure you don't have any old copies of the plugin around.

@Novadestin if you're also talking about a thing that's been going on for months, upgrade.

I should just change the error message so we can distinguish between people who didn't upgrade and people who are getting the temporary server-side issue.

**Comment by Zombie-Ryushu** [comment] 2017-06-07 17:07
Can confirm this, it will continue working as long as you don't get disconnnected. Plugin needs updating.

**Comment by dequis** [comment] 2017-06-07 17:58
Oh well. Not much I can do if I can't reproduce it.

**Comment by arximboldi** [comment] 2017-06-07 18:17
Since Facebook works differently per country, I wonder if that explains why people get it at different times. I am using this from Germany.

**Comment by dequis** [comment] 2017-06-07 18:32
No, it's more complex than that, and I already tried from multiple locations

**Comment by arximboldi** [comment] 2017-06-07 18:43
Damn Facebook, I hate it! 😝

**Comment by Zombie-Ryushu** [comment] 2017-06-07 19:25
This is from US and Canadian FaceBook instances.

**Comment by felagund** [comment] 2017-06-07 20:02
Czechia here.

**Comment by kelpier** [comment] 2017-06-07 20:58
New Zealand here, but my NZ friend using the same plugin is having no trouble.  Seems like the protocol changes are rolled out slowly.  Last time this happened it took a few days before he saw the same error.

**Comment by wision** [comment] 2017-06-08 08:26
@dequis I use CenterIM and purple-facebook plugin from current master.

**Comment by dequis** [comment] 2017-06-08 18:38
0.9.4 includes possibly relevant changes:

* The error message is now "Failed to get sync_sequence_id". If you get the old error message you haven't updated the plugin correctly.
* Bumped the orca version in case it's being blocked because of that (but i doubt it)
* Adding content-type probably won't help, but it's an issue that appeared roughly at the same time, so who knows!

https://github.com/dequis/purple-facebook/releases/tag/v0.9.4-c9b74a765767

**Comment by wision** [comment] 2017-06-08 19:10
Well.. that's weird. I'm still getting the old message. I'll have to investigate, why `make && make install` does not work :/ Thank you

**Comment by kelpier** [comment] 2017-06-08 19:52
Latest version has fixed it for me.

**Comment by wolfy67** [comment] 2017-06-09 06:09
wfm too. thanks, dx

**Comment by arximboldi** [comment] 2017-07-01 10:18
Still happens for me :'(

**Comment by dequis** [comment] 2017-07-01 13:22
If it's the same error message in the title you haven't updated the plugin correctly.

**Comment by arximboldi** [comment] 2017-07-01 15:18
You are right... I forgot I needed to do `autogen.sh` again... It now showed an error about missing queue once, but when I retried it seems to be working now. Thanks so much for the fix and sorry for the noise!

**Comment by pkar70** [comment] 2017-07-21 13:14
I get "Failed to get sync_sequence_id" every time :(

**Comment by dequis** [comment] 2017-07-21 19:12
@pkar70 please open a new issue and send me one of these https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

Locking this one as the original error is gone.

**Comment by dequis** [comment] 2018-03-18 01:51
Closing this (which was only open for visibility)

**Closed by dequis** 2018-03-18 01:51 UTC
Labels: resolved
