### ISSUE TITLE
Connection error: Null value for $.viewer.message_threads.unread_count

### ISSUE THREAD

**Issue by ajarov** [dequis/purple-facebook#394] opened 2017-12-05 12:18 UTC
Can't connect to Facebook anymore, I get the error of the title.
Started happening today.

Windows 7 64-bit
Pidgin 2.12.0 (libpurple 2.12.0)
prpl-facebook 20171004~4aa77de~9ff9acf9fa14~137

**Comment by dequis** [comment] 2017-12-05 12:28
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by ajarov** [comment] 2017-12-05 12:45
Debug log sent via e-mail, thanks.

**Comment by ajarov** [comment] 2017-12-05 17:14
It seems to be solved, I can connect now.

**Comment by dequis** [comment] 2017-12-05 20:03
Duplicate of #393

**Closed by dequis** 2017-12-05 20:03 UTC
