### ISSUE TITLE
Invalid HTTP response code (400) on Facebook file sending or receiving

### ISSUE THREAD

**Issue by db-bogdan** [dequis/purple-facebook#332] opened 2017-06-08 10:33 UTC
Whenever I send a file (via the Facebook website) or whenever I receive a file, my account gets disconnected and I am getting that error.

I am using Pidgin 2.12.0 on Windows and I have downloaded the latest json-glib and facebook plugin today, to no avail.

I am not sure, but I believe this was not happening yesterday.

**Comment by wolfy67** [comment] 2017-06-08 10:52
Since this morning I get the same error when trying to login. Using pidgin-2.12.0 + purple-facebook 0.9.3-c9b74a765767 on CentOS Linux 6.9. I tried multiple times to connect/disconnect/logout/login via web ( actually I was already connected via the web site for several hours before trying to login with pidgin )

**Comment by edarblanco** [comment] 2017-06-08 13:30
I have the same problem, using pidgin 2.12.0 and purple-facebook 0.9.3 on ArchLinux

**Comment by dequis** [comment] 2017-06-08 15:31
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by edarblanco** [comment] 2017-06-08 16:17
Oh my error, ok, the file, and now everything is fine, purple-facebook connects very well, thanks
[pidgin.txt](https://github.com/dequis/purple-facebook/files/1061627/pidgin.txt)

**Comment by dequis** [comment] 2017-06-08 16:31
The page says to not post the logs publicly, they are full of private stuff.

**Comment by edarblanco** [comment] 2017-06-08 16:37
Really?? ok, and how do you think I'll get you the log file? posting??

**Comment by dequis** [comment] 2017-06-08 16:38
Read the instructions in that page

**Comment by dequis** [comment] 2017-06-08 16:54
Found the issue, preparing fix

**Comment by edarblanco** [comment] 2017-06-08 16:57
thanks, changing the facebook pass

**Comment by dequis** [comment] 2017-06-08 18:30
Please test 0.9.4

https://github.com/dequis/purple-facebook/releases/tag/v0.9.4-c9b74a765767

Windows/obs builds will be ready in 10-20 mins.

**Comment by db-bogdan** [comment] 2017-06-08 18:57
Works on Windows. Amazing work! Thank you. You're a star. ★

**Comment by edarblanco** [comment] 2017-06-08 23:27
ok, compiling and work, on Archlinux, thanks, really thanks

**Comment by isakrubin** [comment] 2017-06-09 07:21
still get the same "Invalid HTTP response code (400)" on linux (debian 8), just did a fresh build of 0.9.4, do I need to remove and readd account?

**Comment by avano** [comment] 2017-06-15 18:58
Hi, I can still reproduce the error with this version:

Facebook
	Author: (null)
	Version: 0.9.4-c9b74a765767
	Website: https://github.com/dequis/purple-facebook
	ID String: prpl-facebook
	Loadable: Yes
	Loaded: Yes

It happens when I receive an image. Emailing you the logs

**Comment by dequis** [comment] 2017-06-15 19:08
@avano Thanks for the log. Maybe we can't rely on that plugin information stuff, since you're still using 0.9.3. Relevant parts:

Near the end, in any of the http requests:

```
User-Agent: Facebook plugin / Purple / 0.9.3 [FBAN/Orca-Android;FBAV/38.0.0.22.155;FBBV/14477681]
```

Near the beginning:

```
(20:53:57) plugins: probing /home/avano/.purple/plugins/libfacebook.so
```

And a few lines below:

```
(20:53:57) plugins: probing /usr/lib/purple-2/libfacebook.so
(20:53:57) plugins: Not loading /usr/lib/purple-2/libfacebook.so. Another plugin with the same name (/home/avano/.purple/plugins/libfacebook.so) has already been loaded.
```

So you have the plugin installed twice and it's loading the old version. Remove the old one, which in this case is ~/.purple/plugins/libfacebook.so

I suspect this is the case with other people too.

**Comment by avano** [comment] 2017-06-15 19:16
Hi,

thanks for the quick check, I can confirm that it helped.

P.S. I indeed saw the 0.9.3 at the end of the log but I wasn't sure if the 0.9.4-c9b74a765767 wasn't just a quick snapshot for the test before making a proper release, but now it is clear it was my mistake :+1:

**Comment by wilkerjnc** [comment] 2017-06-21 15:36
Using the current build:

Facebook
	Author: (null)
	Version: 0.9.3-c9b74a765767
	Website: https://github.com/dequis/purple-facebook
	ID String: prpl-facebook
	Loadable: Yes
	Loaded: Yes

but still getting the Invalid HTTP response code (400).

OpenSUSE 42.2
Pidgin 2.12.0 (libpurple 2.12.0)

 uname -a
Linux linux-3wjh.site 4.4.72-18.12-default #1 SMP Mon Jun 19 14:11:41 UTC 2017 (9c03296) x86_64 x86_64 x86_64 GNU/Linux

Here is the output of the debug log: 

[purple-debug_log.txt](https://github.com/dequis/purple-facebook/files/1092038/purple-debug_log.txt)

I can run the windows version of Pidgin under WINE with the current build and it works.

**Comment by dequis** [comment] 2017-06-21 15:49
@wilkerjnc That's not the current build. That's the old one. 0.9.3 not 0.9.4

**Comment by wilkerjnc** [comment] 2017-06-21 16:03
Ooops, apparently there was an older copy in my /home/<user>/.purple/plugins directory.  Removed that and now the issue is solved.  Thanks so much for the direction!

**Comment by dequis** [comment] 2018-03-18 01:50
Closing this (which was only open for visibility)

**Closed by dequis** 2018-03-18 01:50 UTC
Labels: resolved
