### ISSUE TITLE
SSL handshake failure graph.facebook.com

### ISSUE THREAD

**Issue by unnilennium** [dequis/purple-facebook#411] opened 2018-03-27 14:53 UTC
For 2 or 3 weeks now I am unable to connect to fb using purple-facebook ( or at least only able to connect once or two a week)
I have it installed on 3 Fedora desktop  (2 Fedora 26 and  1 Fedora 27). All up to date

$ rpm -q purple-facebook
purple-facebook-0.9.5-1.9ff9acf9fa14.fc26.x86_64

tried without proxy or with default gnome setting (no proxy), tried on multiple connections.

here is the debug log:

(10:45:32) account: Connecting to account XXXX.
(10:45:32) connection: Connecting. gc = XXXX
(10:45:32) http: Performing new request XXXX to graph.facebook.com.
(10:45:32) dnsquery: Performing DNS lookup for graph.facebook.com
(10:45:32) dns: Successfully sent DNS request to child 5062
(10:45:32) dns: Got response for 'graph.facebook.com'
(10:45:32) dnsquery: IP resolved for graph.facebook.com
(10:45:32) proxy: Attempting connection to 31.13.80.8
(10:45:32) proxy: Connecting to graph.facebook.com:443 with no proxy
(10:45:32) proxy: Connection in progress
(10:45:32) proxy: Connecting to graph.facebook.com:443.
(10:45:32) proxy: Connected to graph.facebook.com:443.
(10:45:32) nss: Handshake failed  (-12286)
(10:45:32) socket: invalid state: 3 (should be: 2)(10:45:32) http: Request XXXX performed without success.
(10:45:32) connection: Connection error on XXXX (reason: 0 description: Unable to connect to graph.facebook.com: Échec de la poignée de main SSL)
(10:45:32) account: Disconnecting account XXXX (XXXX)
(10:45:32) connection: Disconnecting connection XXXX
(10:45:32) connection: Destroying connection XXXX

**Comment by dequis** [comment] 2018-03-27 15:06
Duplicate of #408

**Closed by dequis** 2018-03-27 15:06 UTC
