### ISSUE TITLE
pidgin, can't authenticate anymore using an app password

### ISSUE THREAD

**Issue by arnauldb** [dequis/purple-facebook#299] opened 2017-02-25 10:13 UTC
Hello,

I had to change my main fb password today and I changed my app password for pidgin too. But it can't authenticate anymore, I have this error message : 

> Invalid username or password (401)

thank you,

**Comment by JSchwerberg** [comment] 2017-02-25 16:10
+1 here, seeing same behavior.  

```
Pidgin 2.11.0 (libpurple 2.11.0)
f02ebb71b5e32cc4af521e7f89c34dedff8d09ae

Facebook
	Author: (null)
	Version: 20160913~fe06874~66ee77378d82~115
	Website: https://github.com/dequis/purple-facebook
	ID String: prpl-facebook
	Loadable: Yes
	Loaded: Yes
```

**Comment by dequis** [comment] 2017-02-25 17:29
Duplicate of #298

Unfortunately this seems to be an issue with the facebook servers, the official applications don't work with app passwords either.

**Closed by dequis** 2017-02-25 17:29 UTC
