### ISSUE TITLE
Failed to read thrift: api.c:1897 fb_api_cb_publish_pt: assertion 'fb_thrift_read_stop(thft)' failed

### ISSUE THREAD

**Issue by hendricha** [dequis/purple-facebook#495] opened 2020-10-13 07:49 UTC
Hey!

I have the above error immediatly after login. The partner list does not show, but I do get messages, however most of them multiple times.

This happens with a freshly checkedout and recompiled version.

Anyone else has this? / Is there anything else I could provide to help debug this?

**Comment by dequis** [comment] 2020-10-13 13:55
Duplicate of #494

**Closed by dequis** 2020-10-13 13:55 UTC
