### ISSUE TITLE
Hangs in connecting only. Windows version user here..

### ISSUE THREAD

**Issue by quaired** [dequis/purple-facebook#390] opened 2017-11-30 23:42 UTC
Is it just me or everyone is having this problem? This has been going on for the past 2 days already. Maybe needs updating?

**Comment by dequis** [comment] 2017-12-01 13:15
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by quaired** [comment] 2017-12-03 13:21
thanks dequis for your reply.. very much appreciated. i already sent the log to your appropriate email as to this link pointed out. https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by quaired** [comment] 2017-12-03 14:59
Hello dequis,
  Was read all over the issues thread and this fix for 0.9.5 http://dequis.org/libfacebook-20170917-215316e-c9b74a765767.dll solved my issue. It seems my account had too many contacts too.

**Comment by dequis** [comment] 2017-12-04 01:10
Hm. Right. Need to figure out what to do with that one... Oh well.

Closing as duplicate of #366

**Closed by dequis** 2017-12-04 01:10 UTC
