### ISSUE TITLE
Duplicate own messages in group chat

### ISSUE THREAD

**Issue by gkonstanty** [dequis/purple-facebook#226] opened 2016-03-07 11:43 UTC
Is there a way for not duplicate my messages sent from Pidgin in group chat? 
But I don't want to uncheck the "Show self messages" property.

**Comment by tzima** [comment] 2016-03-07 15:31
I confirm the issue. Message appears with a small delay which suggests it's received back from the server. I guess it has something to do with the fact you're listed as a member in the group chat (and message is probably distributed among all of the members).

**Comment by jgeboski** [comment] 2016-03-11 18:15
What [version](https://github.com/jgeboski/purple-facebook/wiki#how-do-i-check-the-current-plugin-version) of the plugin are you using?

**Comment by tzima** [comment] 2016-03-11 18:55
To my knowledge, the latest, `20160215~1af1f6f~92885e0456ed~109`.

![2016-03-11](https://cloud.githubusercontent.com/assets/9641921/13711319/2de33f0e-e7be-11e5-8fb4-0ab4d2052c1e.png)

I looked into the source codes and I think the weak spot is the following condition (facebook.c:499):

	if (isself && !self) {
		continue;
	}

where:

	self = purple_account_get_bool(acct, "show-self", TRUE);
	isself = (msg->flags & FB_API_MESSAGE_FLAG_SELF) != 0;

I suspect `self` is `true`, since I see myself as a group member, and `isself` is also true (since it's my own messaage). Maybe it should only be:

	if (isself) {
		continue;
	}

But this is really just a guess based on a quick look to the source code.

**Comment by jgeboski** [comment] 2016-03-11 19:05
How many times is each message duplicated? Are messages reliably duplicated or is it random? Is it only self messages that are duplicated?

**Comment by tzima** [comment] 2016-03-11 19:09
Only my own messages are exactly once locally duplicated (e.g. I see it twice in Pidgin, but it's not actually sent twice). It occurs reliably, not randomly. Messages from the others are shown properly just once.

**Comment by dequis** [comment] 2016-03-11 19:20
Can't reproduce it here either.

@tzima it's unlikely that those conditions are the issue, those do/did the job right. Something changed server-side.

**Comment by jgeboski** [comment] 2016-03-11 19:21
I cannot reproduce either. What other plugin do you have enabled?

**Comment by tzima** [comment] 2016-03-11 19:51
I tried disabling all other plugins and restarting Pidgin, but the issue remains. It happens both on my desktop and laptop (Pidgin 2.10.9 everywhere). Maybe something really changed server-side? I didn't use group chat until recently, so I can't really tell.

**Comment by dequis** [comment] 2016-03-11 20:01
@gkonstanty what version of pidgin and what version of this plugin?

**Comment by EionRobb** [comment] 2016-03-11 23:39
Duplicate messages happens for me sometimes, but when it does it will happen for just one chat at a time. Happens at work to a coworker too. Haven't worked out a pattern yet.

**Comment by gkonstanty** [comment] 2016-03-16 16:43
It's exactly how tzima describes it, I'm getting back every message send from pidgin. I've got the last (92885e0456ed) version of plugin and the last version of pidgin (Pidgin 2.10.12 (libpurple 2.10.12)). Also I'm working on archlinux

**Comment by dequis** [comment] 2016-03-24 00:10
Can reproduce in only one groupchat of one of my accounts. Diff between the messages that come from the server in response to messages sent to two different groupchats:

```diff
--- bad
+++ good
@@ -1,21 +1,18 @@
 {
   "deltas": [
     {
-      "deltaNewMessage": {
+      "deltaSentMessage": {
         "messageMetadata": {
           "threadKey": {
             "threadFbId": <thread>
           },
           "messageId": <mid>,
           "offlineThreadingId": <tid>,
-          "actorFbId": <me>,
           "timestamp": <timestamp>,
           "tags": [
             "source:chat:orca"
           ]
         },
-        "body": "boop",
-        "ttl": 0,
         "attachments": []
       }
     }
```

**Comment by dequis** [comment] 2016-03-27 02:48
Diff between the echo of a message sent to a buggy groupchat, and a message sent right afterwards from the web interface.

```diff
--- orca
+++ web
@@ -1,25 +1,25 @@
 {
     "deltas": [
         {
             "deltaNewMessage": {
                 "messageMetadata": {
                     "threadKey": {
                         "threadFbId": <thread>
                     },
                     "messageId": <mid>,
                     "offlineThreadingId": <tid>,
                     "actorFbId": <me>,
                     "timestamp": <timestamp>,
                     "tags": [
-                        "source:chat:orca"
+                        "source:chat:web"
                     ]
                 },
                 "body": "beep",
                 "attachments": [],
                 "ttl": 0
             }
         }
     ],
     "firstDeltaSeqId": <seq>,
     "lastIssuedSeqId": <seq>
 }
```

Kinda cheating with the diff since I modified the fields that change every time to `<timestamp>` or `<mid>` but it illustrates that it's indistinguishable from a message

Also, the same issue happens in orca 64.0 (latest version), but with thrift instead of json and that one is a bit harder to censor, so not posting the log. (Note to self, grep for `Log opened Fri Mar 25`)

**Comment by manavortex** [comment] 2016-04-04 12:54
I can duplicate this flawlessly on bitlbee-facebook. Would be interested in a solution :)

**Comment by christophschw** [comment] 2016-04-29 14:33
I can confirm this bug in 66ee77378d82
Would be great to have fixed this because the command execute plugin is triggered every time I send a message.
Thanks!

**Comment by SiSchae** [comment] 2016-05-10 09:59
I'm getting the same error. I'm using latest version from github.

**Comment by fangfufu** [comment] 2016-05-10 14:06
I am getting the same problem with the latest version of the pluggin.

**Comment by vevelonel** [comment] 2016-07-05 13:40
I can confirm that I am also experiencing this issue with the latest versions of both the plugin and the pidgin software.

**Comment by ewtoombs** [comment] 2016-07-08 02:36
I don't know the intention of the "Show self messages" property, but surely it wasn't repeating your own messages twice every time. So what was the intention of that setting? This could be made more clear in its name or in a tooltip.

**Comment by fangfufu** [comment] 2016-07-08 02:39
@ewtoombs, the intention of the setting was to relay other clients' messages to Pidgin. For example, if you send a message on the web client or through your phone, your own message would  be copied to Pidgin too. However currently there seems to be a bug so self-message isn't working for group messages.

**Comment by ewtoombs** [comment] 2016-07-08 02:44
@fangfufu oic.

**Comment by dequis** [comment] 2016-07-08 03:56
>However currently there seems to be a bug so self-message isn't working for group messages

Not working? News to me. Please open a new ticket!

(Unless you refer to this ticket, which isn't really self-messages not working)

**Comment by fangfufu** [comment] 2016-07-08 07:02
Sorry, what I meant is that you get two self-messages.

**Comment by sea3pea0** [comment] 2016-07-16 22:44
I am experiencing this issue with pidgin and facebook purple on windows with latest version of both installed

**Comment by roberthawdon** [comment] 2016-08-12 17:26
I finally got myself two friends (Mr. Billy Nomates here :laughing: ) and I am too experiencing this issue. I am using the latest github build of the plugin and Pidgin 2.10.12 on Ubuntu 16.04

**Comment by tbx1024** [comment] 2016-09-07 10:19
Can confirm, running Pidgin 2.11.0-1 (libpurple 2.11.0) with the plugin version 66ee77378d82 on Fedora 24. This seems to only happen in group chats.

**Comment by m-urban** [comment] 2016-09-09 13:52
Confirming this bug, too, with spectrum.

**Comment by norill** [comment] 2016-09-21 14:41
i also have this issue, can reproduce

**Comment by paly2** [comment] 2016-09-24 09:26
I confirm this issue too

**Comment by dequis** [comment] 2016-11-21 13:46
Likely fixed with https://github.com/dequis/purple-facebook/releases/tag/v0.9.0-c9b74a765767

**Closed by dequis** 2016-11-21 13:46 UTC
Labels: bug
