### ISSUE TITLE
Messages aren't always properly marked as read.

### ISSUE THREAD

**Issue by truenicoco** [dequis/purple-facebook#396] opened 2017-12-08 08:59 UTC
I've seen this occur using Pidgin and Gajim or Conversations throught spectrum2/prosody.

I cannot tell exactly when, but sometimes messages aren't marked as read. This results in messages being received numerous times, including self messages. I think disable "show unread" fixes the issue but I'd rather receive duplicates than miss messages for now. When it happens, the only fix I've found is to go to messenger.com or facebook.com and manually click on the messages. I'd be happy to help debug this issue, let me know if I can.

**Comment by dequis** [comment] 2017-12-08 14:41
Duplicate of #221

**Closed by dequis** 2017-12-08 14:41 UTC

**Comment by truenicoco** [comment] 2017-12-08 15:21
I'm not entirely sure this is an exact duplicate of the #221, as sometimes messages are marked as read, and sometimes they aren't, even though the chat window had focus. However, an option to auto-mark every message as read as soon as they are delivered would definitely solve the problem for me!

**Comment by dequis** [comment] 2017-12-08 15:47
Spectrum has no way to communicate chat window focus. So it has no way to mark messages as read. The only messages that are marked as read are the replied ones.

**Comment by truenicoco** [comment] 2017-12-08 15:59
Oh OK I guess it makes #221 even more important then. I didn't even realize that after more than 1 month of using it.
