### ISSUE TITLE
Failed to read fixed header (proxy related issue)

### ISSUE THREAD

**Issue by dann1** [dequis/purple-facebook#190] opened 2016-01-08 20:54 UTC
Greetings my name is Daniel Clavijo Coca I live in Havana Cuba and I'm trying to use purple-facebook plugin. I downloaded from you the .deb package, Pidgin is now able to use the new option Facebook in the protocol selection, after I introduce all my data (I use proxy) correctly it sais "Fail to read Fixed Header" but it connects somehow because when i do not save the password Pidgin Authentication window prompts, even once it read some old conversations i made long ago. I tried using both username and mail account, I suppose the username is the characters before @facebook.com.  I use debian 8.2.
Thanks for your attention 
![screenshot from 2016-01-08 15 50 27](https://cloud.githubusercontent.com/assets/16429804/12209243/bba11788-b61f-11e5-941e-c49cf2dc80e7.png)

**Comment by jgeboski** [comment] 2016-01-08 20:59
Is this a duplicate of #177?

**Comment by dann1** [comment] 2016-01-08 21:09
don't know let me see

**Comment by dann1** [comment] 2016-01-08 21:09
I updated the image

**Comment by dann1** [comment] 2016-01-08 21:12
Don' know about the SSL certificate it just says failed to read fied header, y use http proxy

**Comment by jgeboski** [comment] 2016-01-14 23:57
Can you send me a [debugging log](https://github.com/jgeboski/purple-facebook/wiki/Debugging-Logs)?

**Comment by dann1** [comment] 2016-01-15 20:45
well finally i tried it, it works for a while and then i dont know why it crashes again saying the same thing, wht is a debugging log I'll check your link

**Comment by dann1** [comment] 2016-01-15 20:46
well now it says something about SSL

**Comment by dann1** [comment] 2016-01-15 20:46
specifically "Unable to connect to graph.facebook.com: SSL Connection Failed"

**Comment by jgeboski** [comment] 2016-01-15 21:41
I cannot do much for you with a [debugging log](https://github.com/jgeboski/purple-facebook/wiki/Debugging-Logs).

**Closed** 2017-01-30 20:33 UTC
Labels: probably not a bug
