### ISSUE TITLE
SSL Handshake Error

### ISSUE THREAD

**Issue by sumdog** [dequis/purple-facebook#409] opened 2018-03-19 16:24 UTC
Just this week I've started getting SSL Handshake errors with the Facebook Graph API. I know they recently depreciated an older version of their API; got some e-mails about it for one of my other projects. Not sure if that's affected purple-facebook. Here's what I see in my Pidgin logs:

```
(11:21:09) dnsquery: IP resolved for graph.facebook.com
(11:21:09) proxy: Attempting connection to 157.240.2.20
(11:21:09) proxy: Connecting to graph.facebook.com:443 with no proxy
(11:21:09) proxy: Connection in progress
(11:21:09) proxy: Connecting to graph.facebook.com:443.
(11:21:09) proxy: Connected to graph.facebook.com:443.
(11:21:09) nss: Handshake failed  (-12286)
(11:21:09) socket: invalid state: 3 (should be: 2)(11:21:09) http: Request 0x395c000 performed without success.
(11:21:09) connection: Connection error on 0x317add0 (reason: 0 description: Unable to connect to graph.facebook.com: SSL Handshake Failed)
```

I'm currently using purple-facebook 20170831 on Gentoo.

**Comment by dequis** [comment] 2018-03-19 16:30
Duplicate of #408 

Upgrade to 2.13.0 or see workaround in my comment there.

**Closed by dequis** 2018-03-19 16:30 UTC
