### ISSUE TITLE
SSL Error on Linux

### ISSUE THREAD

**Issue by PersistentHandle** [dequis/purple-facebook#432] opened 2018-08-10 08:24 UTC
Disconnected with error: "Unable to connect to b-api.facebook.com: SSL Handshake Failed"

On Linux Mint MATE Tara 19 (based on Ubuntu 18.04), using Facebook's App Passwords for login.

**Comment by dequis** [comment] 2018-08-10 17:30
https://github.com/dequis/purple-facebook/issues/408#issuecomment-374275285

**Comment by uNouss** [comment] 2018-08-12 15:41
I have the same issue. 
I follow #408 and I config NSS Preference plugin like this:

![img](http://i.imgur.com/UkNNsVp.png)

but it's not work

![](http://i.imgur.com/UIGoFKC.png)

**Comment by dequis** [comment] 2018-08-12 19:30
That's not the same issue because it's not "SSL Handshake Failed", that's some other connection error. Please open a new issue and we'll talk it over there.

**Comment by janek37** [comment] 2018-09-20 12:32
I'm getting a similar error after upgrade to Ubuntu 18.04:
[account name] disconnected
Unable to connect to graph.facebook.com: SSL Handshake Failed

**Comment by dequis** [comment] 2018-09-21 02:44
@janek37 Again, see: https://github.com/dequis/purple-facebook/issues/408#issuecomment-374275285

**Comment by dequis** [comment] 2019-01-13 23:31
Duplicate of #408

**Closed by dequis** 2019-01-13 23:31 UTC
