### ISSUE TITLE
purple-facebook does not support the latest messenger protocols

### ISSUE THREAD

**Issue by TimMagee** [dequis/purple-facebook#313] opened 2017-03-30 16:49 UTC
http://www.dnaindia.com/scitech/report-facebook-messenger-to-no-longer-work-on-windows-smartphones-2375047
While the headline of this article is a little misleading (Messenger still works in Windows 10), I believe this is the heart of the recent problems with purple-facebook. Until purple-facebook supports the new messenger protocol it will not work at all because facebook discontinued the old one.

**Comment by sumdog** [comment] 2017-03-30 17:06
Can confirm I've seen this today in Pidgin 2.12.0 and purple-facebook-20161121::jorgicio (Gentoo overlay):

    Null value for $.viewer.message_threads.sync_sequence_id

**Comment by Konrad127123** [comment] 2017-03-30 17:55
I also had this problem.The problem is fixed in the version uploaded to Git today ( 3cbb433d12ba04111fd0ba3e6c86dac72cfc83a4 )

**Comment by TimMagee** [comment] 2017-03-30 18:07
Any idea when the ppa will be updated?

**Comment by dequis** [comment] 2017-03-30 19:37
We already have a ticket for this, #306

Get the latest release from https://github.com/dequis/purple-facebook/releases

The APT repository updates automatically a few minutes after each commit. So it already is up to date.

**Closed by dequis** 2017-03-30 19:37 UTC
