### ISSUE TITLE
stuck connecting

### ISSUE THREAD

**Issue by ProximaSolaris** [dequis/purple-facebook#400] opened 2018-01-07 02:22 UTC
hi there! 

for the last 2 days pidgin has been unable to connect to facebook. it's not giving me any errors, just stays stuck on the connecting status info. the system log isn't giving me any information - just people join/parting. i've tried redownloading the plugin without success. is there a setting i need to change? or should i just wait for a fresh update?

thanks!

**Comment by dequis** [comment] 2018-01-07 04:48
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by ProximaSolaris** [comment] 2018-01-07 06:53
log after 90min of running: 

Loaded exchndl.dll
 Setting exchndl.dll LogFile to C:\Windows\TEMP\pidgin.RPT
 Setting exchndl.dll DebugInfoDir to c:\Program Files (x86)\Pidgin\pidgin-2.12.0-dbgsym
GTK+ path found: c:\Program Files (x86)\Pidgin\Gtk\bin
Using SetDllDirectory
Setting locale: LANG=en
Prefix='c:\Program Files (x86)\Pidgin\spellcheck'
Looking for modules in dir='C:\Users\xxxxx\AppData\Local\enchant'
Looking for modules in dir='C:\Users\xxxxx\enchant'
Looking for modules in dir='c:\Program Files (x86)\Pidgin\spellcheck\lib\enchant'

**Comment by dequis** [comment] 2018-01-07 17:25
Sorry, I don't think you have followed the instructions correctly, try again more carefully. Also, first step says "Read the important information at the top" and that information says that you should not post it publicly, please don't.

**Comment by ProximaSolaris** [comment] 2018-01-07 21:42
sorry, i thought posting a censored version of the log here would be ok. but that's ok. i've emailed you with a fresh debug file.

**Comment by dequis** [comment] 2018-01-08 04:34
So:

* 08:15:51 - Starts pidgin
* 08:15:52 - Starts login
* 08:15:55 - Gets first contacts response, `"has_next_page":true`
* 08:15:56 - Gets second contacts response, `"has_next_page":false`
* Nothing happens
* 08:29:38 - Quits pidgin

Uh.

I suspect this isn't exactly the same as #366, but, try the build linked in this comment https://github.com/dequis/purple-facebook/issues/366#issuecomment-330022164 and report results

**Comment by ProximaSolaris** [comment] 2018-01-08 05:39
That seems to have fixed it! Thank you so much for dealing with this so quickly!

**Comment by dequis** [comment] 2018-01-08 14:49
Neat. Closing as duplicate of #366 then, but i'll make a note to consider your logs too when fixing it.

**Closed by dequis** 2018-01-08 14:49 UTC
