### ISSUE TITLE
links are not displayed

### ISSUE THREAD

**Issue by ychromosome** [dequis/purple-facebook#461] opened 2019-05-10 17:44 UTC
I have a friend who also uses pidgin. when I send him a link like this one: https://www.notebookcheck.com/ThinkPad-T495-T495s-X395-Lenovo-setzt-erstmals-AMD-Ryzen-in-den-T-X-ThinkPads-ein.420323.0.html he does not recieve it in pidgin but it is displayed on the facebook website.
it also does not work vice versa.

we are both on the latest plugin version. any ideas?

**Comment by dequis** [comment] 2019-05-11 02:43
Duplicate of #460

**Closed by dequis** 2019-05-11 02:43 UTC
