### ISSUE TITLE
Invalid HTTP response code (400) on connect

### ISSUE THREAD

**Issue by isakrubin** [dequis/purple-facebook#333] opened 2017-06-09 12:16 UTC
get the same "Invalid HTTP response code (400)" on linux (debian 8), just did a fresh build of 0.9.4

This is when connecting or reconnecting, when connecting it shows contacts and messages for a second before it disconnects due to the 400 result.

Facebook
	Author: (null)
	Version: 0.9.4-c9b74a765767
	Website: https://github.com/dequis/purple-facebook
	ID String: prpl-facebook
	Loadable: Yes
	Loaded: Yes

(09:23:08) account: Connecting to account XXXXX.
(09:23:08) connection: Connecting. gc = 0x55fbbec24d80
(09:23:08) http: Performing new request 0x55fbc1090f00 to b-api.facebook.com.
(09:23:08) dnsquery: Performing DNS lookup for b-api.facebook.com
(09:23:08) dns: Successfully sent DNS request to child 18498
(09:23:08) dns: Got response for 'b-api.facebook.com'
(09:23:08) dnsquery: IP resolved for b-api.facebook.com
(09:23:08) proxy: Attempting connection to 31.13.86.37
(09:23:08) proxy: Connecting to b-api.facebook.com:443 with no proxy
(09:23:08) proxy: Connection in progress
(09:23:08) proxy: Connecting to b-api.facebook.com:443.
(09:23:08) proxy: Connected to b-api.facebook.com:443.
(09:23:08) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 256-bit ECDSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
(09:23:08) nss: subject=CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=California,C=US issuer=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(09:23:08) nss: partial certificate chain
(09:23:08) certificate/x509/tls_cached: Starting verify for b-api.facebook.com
(09:23:08) certificate/x509/tls_cached: Checking for cached cert...
(09:23:08) certificate/x509/tls_cached: ...Found cached cert
(09:23:08) nss/x509: Loading certificate from /home/x/.purple/certificates/x509/tls_peers/b-api.facebook.com
(09:23:08) certificate/x509/tls_cached: Peer cert matched cached
(09:23:08) nss/x509: Exporting certificate to /home/x/.purple/certificates/x509/tls_peers/b-api.facebook.com
(09:23:08) util: Writing file /home/x/.purple/certificates/x509/tls_peers/b-api.facebook.com
(09:23:08) nss: Trusting CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=California,C=US
(09:23:08) certificate: Successfully verified certificate for b-api.facebook.com
(09:23:08) http: Request 0x55fbc1090f00 performed without success.
(09:23:08) connection: Connection error on 0x55fbbec24d80 (reason: 16 description: Invalid HTTP response code (400))

**Comment by dequis** [comment] 2017-06-09 15:52
https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

**Comment by juliokarl** [comment] 2017-06-09 18:52
i had the same problem 400 since 1 week or so without changing anything. 
Now installed the package from dequis, he linked it in another thread:
https://github.com/dequis/purple-facebook/releases/tag/v0.9.4-c9b74a765767
and now it works perfectly again.

**Comment by dequis** [comment] 2017-06-10 20:05
@isakrubin hello?

**Comment by dequis** [comment] 2017-06-10 20:07
Actually, I'm going to close this for now since it's confusing to have it open

The main issue is #332 which is already fixed.

I don't know why your 0.9.4 doesn't work since it was a straightforward issue that I reproduced locally.

**Closed by dequis** 2017-06-10 20:07 UTC

**Comment by dequis** [comment] 2017-06-15 19:11
Copying what I wrote in some other ticket since it's relevant here too:

It looks like the plugin information dialog isn't reliable, sadly. See this comment: https://github.com/dequis/purple-facebook/issues/332#issuecomment-308838543

Maybe you want to check that for yourself, but if it looks okay or if you're not sure what's going on, send me a debugging log https://github.com/dequis/purple-facebook/wiki/Debugging-Logs
