### ISSUE TITLE
Receiving duplicated messages

### ISSUE THREAD

**Issue by lmfardin** [dequis/purple-facebook#448] opened 2018-12-27 13:57 UTC
Sometimes I receive the same message 2 or 3 times right after my messages are sent.
For instance:
- I send a message
- I get a response
- I send another message
- I get the same response about 10 seconds later
I confirmed on Messenger that it only happens on Pidgin.

**Comment by dequis** [comment] 2019-01-05 00:14
Duplicate of https://github.com/dequis/purple-facebook/issues/280

**Closed by dequis** 2019-01-05 00:14 UTC
